name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Display SoftUni Username
      run: echo 'PeterBoyadzhiev'

  run-ui-tests:
      needs: build-and-test
      runs-on: ubuntu-latest

      steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Install PlayWright browsers
        run: npx playwright install
      - name: Start the application
        run: npm run start &
      - name: Execute UI tests
        run: npm run test:ui

  deploy:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true